trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3'
  displayName: Use latest Python 3

- script: |
    python -m pip install --upgrade pip
    pip install wheel
  displayName: Install dependencies

- script: make
  displayName: make
